### ISSUE TITLE
[Request] Twilio Programmable Chat 

### ISSUE THREAD

**Issue by alberk8** [armackey/twilio-video-angular-setup#1]
Hi,

I really like that you have started to implement the Twillio Video for Angular 5, would you consider to do so for the Programmable Chat?  Thank you.

**Comment by armackey** [comment]
Hmm.. maybe but probably not in the near future.

**Comment by alberk8** [comment]
I am starting with angular 2/5 and do not have the expertise to get the javascript into angular framework.  Do you have any advise and/or pointers as to where to start.  Thank you.

**Comment by armackey** [comment]
Hmm.. sort of need to have some basic understanding of Typescript. Look into sibling components communicating. Dependency injection, input, output, ViewChild (the many more decorators that I'm missing). There's also life cycles but the only one's i've really used are ngOnInit and ngOnDestroy.

For the most part, it's gonna feel overwhelming. Angular 2/5 is not an easy pick up and go framework. It's gonna feel frustrating. Don't give up.

Start with youtube videos on Typescript. Then look into Angular.

Good luck!

**Comment by alberk8** [comment]
Thank you for the pointers.
